# Generated by Django 3.1.5 on 2021-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugerencia',
            options={'ordering': ['orden', 'nombreES'], 'verbose_name': 'sugerencia del cheff', 'verbose_name_plural': 'sugerencias del cheff'},
        ),
        migrations.RenameField(
            model_name='sugerencia',
            old_name='descripionEN',
            new_name='descripcionEN',
        ),
        migrations.RenameField(
            model_name='sugerencia',
            old_name='descripionES',
            new_name='descripcionES',
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='orden',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
