# Generated by Django 3.1.5 on 2021-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210310_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugerencia',
            options={'ordering': ['-orden', 'precio'], 'verbose_name': 'sugerencia del cheff', 'verbose_name_plural': 'sugerencias del cheff'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripionEN',
            new_name='descripcionEN',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripionES',
            new_name='descripcionES',
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='descripionEN',
            new_name='descripcionEN',
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='descripionES',
            new_name='descripcionES',
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='descripcionEN',
            field=models.TextField(max_length=200, verbose_name='Descripción en inglés'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='descripcionES',
            field=models.TextField(max_length=200, verbose_name='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='nombreEN',
            field=models.CharField(max_length=150, verbose_name='Nombre del plato en inglés'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='nombreES',
            field=models.CharField(max_length=150, verbose_name='Nombre del plato en español'),
        ),
    ]
