# Generated by Django 3.1.5 on 2021-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210310_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcionEN',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcionES',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcionEN',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcionES',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
    ]
