# Generated by Django 3.1.5 on 2021-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210310_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcionEN',
            field=models.TextField(max_length=200, verbose_name='Descripción en inglés'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcionES',
            field=models.TextField(max_length=200, verbose_name='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tituloEN',
            field=models.CharField(max_length=150, verbose_name='Título en inglés'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tituloES',
            field=models.CharField(max_length=150, verbose_name='Título en español'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcionEN',
            field=models.TextField(max_length=200, verbose_name='Descripción en inglés'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcionES',
            field=models.TextField(max_length=200, verbose_name='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombreEN',
            field=models.CharField(max_length=150, verbose_name='Nombre del plato en inglés'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombreES',
            field=models.CharField(max_length=150, verbose_name='Nombre del plato en español'),
        ),
    ]
