# Generated by Django 3.1.5 on 2021-03-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraseES', models.CharField(max_length=200, verbose_name='Frase')),
                ('fraseEN', models.CharField(max_length=200, verbose_name='Frase')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['autor'],
            },
        ),
    ]
