# Generated by Django 3.1.5 on 2021-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fraseEN',
            field=models.TextField(max_length=200, verbose_name='Frase en inglés'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fraseES',
            field=models.TextField(max_length=200, verbose_name='Frase en español'),
        ),
    ]
