# Generated by Django 3.1.5 on 2021-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreES', models.CharField(max_length=150, verbose_name='Nombre del evento en español')),
                ('nombreEN', models.CharField(max_length=150, verbose_name='Nombre del evento en inglés')),
                ('descripcionES', models.TextField(max_length=200, verbose_name='Descripción en español')),
                ('descripcionEN', models.TextField(max_length=200, verbose_name='Descripción en inglés')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
